apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: ticketing
build:
  local:
    push: false
  artifacts:
    - image: philnguyensherlock/auth
      context: auth
      docker:
        dockerfile: Dockerfile
    - image: philnguyensherlock/ticketing-client
      context: client
      docker:
        dockerfile: Dockerfile
    - image: philnguyensherlock/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
    - image: philnguyensherlock/orders
      context: orders
      docker:
        dockerfile: Dockerfile
    - image: philnguyensherlock/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
    - image: philnguyensherlock/payments
      context: payments
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - infra/k8s/*
