apiVersion: apps/v1
kind: Deployment
metadata: 
  name: auth-depl
  
spec:
  replicas: 1 # number of pods we want to create running
  selector: # tell the deployment how to find all the pods that is going to create
    matchLabels: 
      app: auth
  template: 
    metadata: 
      labels: 
        app: auth
    spec: 
      containers: 
        - name: auth
          image: philnguyensherlock/auth
          env: 
            - name: MONGO_URI
              value: 'mongodb://auth-mongo-srv:27017/auth'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY

---
apiVersion: v1
kind: Service
metadata: 
  name: auth-srv
spec:
  selector: 
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000